print("enter the no. whose cube table you want to know")
a = int(input())
print(a*1 ** 3)
print(a*2 ** 3)
print(a*3 ** 3)
print(a*4 ** 3)
print(a*5 ** 3)
print(a*6 ** 3)
print(a*7 ** 3)
print(a*8 ** 3)
print(a*9 ** 3)
print(a*10 ** 3)