print("enter the no. whose square table you want to know")
a = int(input())
print(a*1 ** 2)
print(a*2 ** 2)
print(a*3 ** 2)
print(a*4 ** 2)
print(a*5 ** 2)
print(a*6 ** 2)
print(a*7 ** 2)
print(a*8 ** 2)
print(a*9 ** 2)
print(a*10 ** 2)